{{- with .Values.networkTuning.interfaceMTUs }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-watcher-cluster-binding
  namespace: openshift-config
subjects:
  - kind: ServiceAccount
    name: mcp-watcher
    namespace: openshift-config
roleRef:
  kind: ClusterRole
  name: mcp-watcher-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}