{{- with .Values.networkTuning.interfaceMTUs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wait-for-mcp-script
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  wait-for-mcp.sh: |
    #!/bin/bash
    set -e
    echo "Waiting for all MachineConfigPools to finish updating..."
    while true; do
      updating=$(oc get machineconfigpools -o jsonpath='{range .items[*]}{.metadata.name} {.status.conditions[?(@.type=="Updating")].status}{"\n"}{end}' | grep " True" || true)
      if [[ -z "$updating" ]]; then
        echo "All MachineConfigPools have finished updating."
        break
      else
        echo "Still updating: $updating"
        sleep 60
      fi
    done
{{ end }}