{{ if .Values.driverTuning.ixgb }}
---
apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: ixgb-driver-tuning
  namespace: openshift-cluster-node-tuning-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  profile:
  - data: |
      [main]
      summary=Increase throughput for NICs using ixgb driver
      include=openshift-node
      [sysctl]
      ### CORE settings (mostly for socket and UDP effect)
      # Set maximum receive socket buffer size.
      net.core.rmem_max = 524287
      # Set maximum send socket buffer size
      net.core.wmem_max = 524287
      # Set default receive socket buffer size.
      net.core.rmem_default = 524287
      # Set default send socket buffer size.
      net.core.wmem_default = 524287
      # Set maximum amount of option memory buffers.
      net.core.optmem_max = 524287
      # Set number of unprocessed input packets before kernel starts dropping them.
      net.core.netdev_max_backlog = 300000
    name: ixgb-driver-tuning
  recommend:
  - match:
    - label: node-role.kubernetes.io/master
    - label: node-role.kubernetes.io/worker
    - label: node-role.kubernetes.io/control-plane
    priority: 20
    profile: ixgb-driver-tuning
{{ end }}