{{- with .Values.nodeTuning }}
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: master
  labels:
    increase-system-resources: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{ end }}