{{- with .Values.networkTuning.clusterNetworkMTUs }}
---
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  migration:
{{ toYaml . | nindent 4 }}
{{- end }}