{{- with .Values.networkTuning.interfaceMTUs }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-watcher
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
{{- end }}