{{- with .Values.networkTuning.interfaceMTUs }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-watcher
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcp-watcher-role
  namespace: openshift-config
rules:
  - apiGroups: ["machineconfiguration.openshift.io"]
    resources: ["machineconfigpools"]
    verbs: ["get", "list", "watch"]
{{- end }}