---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dataobjects-modifier
  namespace: openshift-virtualization-os-images
rules:
  - apiGroups: ["cdi.kubevirt.io"]
    resources: ["datavolumes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["cdi.kubevirt.io"]
    resources: ["datasources"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-dataobject-modification
  namespace: openshift-virtualization-os-images
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dataobjects-modifier
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: windows-virtualization-setup