---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: registry
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  to:
    kind: Service
    name: image-registry
    weight: 100
  tls:
    termination: reencrypt
