---
apiVersion: v1
kind: ConfigMap
metadata:
  name: image-set-configuration
  labels:
    app.kubernetes.io/name: image-set-configuration
    app.kubernetes.io/part-of: mirror-update-content
data:
  imagesetconfiguration.yaml: |
    ---
    apiVersion: mirror.openshift.io/v1alpha2
    kind: ImageSetConfiguration
    storageConfig:
      registry:
        imageURL: {{ .Values.destinationRegistry.host }}/oc-mirror-connected-metadata:latest
        skipTLS: {{ .Values.destinationRegistry.skipTLS | default false }}
    mirror:
{{- toYaml .Values.whatToMirror | nindent 6 }}
