---
apiVersion: batch/v1
kind: Job
metadata:
  name: run-oc-mirror
  labels:
    app.kubernetes.io/name: run-oc-mirror
    app.kubernetes.io/component: oc-mirror-job
    app.kubernetes.io/part-of: mirror-ocp-content
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: run-oc-mirror
        app.kubernetes.io/component: oc-mirror-job
        app.kubernetes.io/part-of: mirror-update-content
    spec:
      restartPolicy: OnFailure
      serviceAccountName: oc-mirror-sa
      containers:
        - name: run-oc-mirror
          image: {{ .Values.openshiftToolsImage }}
          env:
            - name: REGISTRY
              value: {{ .Values.destinationRegistry.host }}
            - name: DEST_USE_HTTP
              value: '{{ .Values.destinationRegistry.useHttp | default false }}'
            - name: DEST_SKIP_TLS
              value: '{{ .Values.destinationRegistry.skipTls | default false }}'
          command:
            - /bin/bash
            - -c
            - |
              # Download oc-mirror
              cd /tmp
              curl https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/oc-mirror.tar.gz -o oc-mirror.tar.gz
              tar -xzvf oc-mirror.tar.gz
              chmod +x oc-mirror
{{ if .Values.destinationRegistry.internalRegistry }}
              # Login to registry
              oc registry login --to=/.docker/destination-registry.json
              # Combine pull secret and registry auth
              jq -s 'reduce .[] as $item ({}; .auths += $item.auths)' "/tmp/pull-secret/config.json" "/.docker/destination-registry.json" > /.docker/config.json
{{ end }}
              # Run oc-mirror
              ./oc-mirror --config=/tmp/imagesetconfiguration.yaml docker://"$REGISTRY" --dest-use-http=$DEST_USE_HTTP --dest-skip-tls=$DEST_SKIP_TLS --max-nested-paths=2 --skip-pruning=true
          volumeMounts:
            - name: run-oc-mirror-configs
              mountPath: /tmp/imagesetconfiguration.yaml
              subPath: imagesetconfiguration.yaml
            - name: dot-kube
              mountPath: /.kube
            - name: run-containers
              mountPath: /run/containers
            - name: docker-dir
              mountPath: /.docker
            - name: pull-secret
              mountPath: /tmp/pull-secret
              readOnly: false
      volumes:
        - name: run-oc-mirror-configs
          configMap:
            name: image-set-configuration
        - name: dot-kube
          emptyDir:
            sizeLimit: 100Mi
        - name: run-containers
          emptyDir:
            sizeLimit: 100Mi
        - name: docker-dir
          emptyDir:
            sizeLimit: 100Mi
        - name: pull-secret
          secret:
            secretName: pull-secret
