---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-full-access-binding
subjects:
  - kind: ServiceAccount
    name: oc-mirror-sa
roleRef:
  kind: Role
  name: registry-full-access
  apiGroup: rbac.authorization.k8s.io