---

- name: Create or delete a virtual machine to run Image Builder
  hosts:
    - all
  gather_facts: false
  vars:
    ocp_resource_state: present
  module_defaults:
    group/k8s:
      namespace: "{{ openshift_namespace }}"
  tasks:
    - name: Deploy/delete virtual machine and resources
      kubernetes.core.k8s:
        template:
          - path: templates/virtual-machine/virtualmachine.yaml.j2
          - path: templates/virtual-machine/service.yaml.j2
          - path: templates/virtual-machine/route.yaml.j2
        state: "{{ ocp_resource_state }}"