---

- name: Wait for Image Builder server to be reachable
  hosts:
    - all
  gather_facts: false
  tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        timeout: 600
    - name: Run the setup module for good measure
      ansible.builtin.setup:
