---
apiVersion: v1
kind: Secret
metadata:
  name: rpm-ostree-lifecycle-management-repo-github-access
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/RedHatEdge/acp-operations.git
  password: {{ .Values.githubPAT }}
